import { Inter } from 'next/font/google';
import './globals.css';
import Head from 'next/head';

import { AppContextProvider } from '@/app/contexts/AppContext';
import Navbar from '@/app/components/Navbar/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <Head>
      <link rel="stylesheet" href="https://use.typekit.net/vxz2phk.css"/>
      </Head>
      <body className={inter.className}>
        <AppContextProvider>
          <Navbar />
          {children}
        </AppContextProvider>
      </body>
    </html>
  );
}
